trigger:
  branches:
    include:
      - uno
      - beta
      - release/beta/*
      - stable
      - release/stable/*

  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    # don't trigger the CI if only docs files are changed
    - doc/*
    - '**/*.md'
    - '*.md'

pr: 
  branches:
    include:
      - uno
      - beta
      - release/beta/*
      - stable
      - release/stable/*

  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    # don't trigger the CI if only docs files are changed
    - doc/*
    - '**/*.md'
    - '*.md'

variables:
  # Path where packages (nuget or app packages) will be copied to.
  PackageOutputPath: $(build.artifactstagingdirectory)

  IsCanaryBranch: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries/')]
  IsReleaseBranch: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))]
  XCODE_ROOT: '/Applications/Xcode_16.1.app'

jobs:
- template: build/workflow/stage-build-packages.yml
- template: build/workflow/stage-build-windows.yml
- template: build/workflow/stage-build-android.yml
- template: build/workflow/stage-build-ios-catalyst.yml
- template: build/workflow/stage-build-wasm.yml
- template: build/workflow/stage-build-skia-desktop.yml