<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetCurrentAll)</TargetFrameworks>
    <Product>$(AssemblyName) ($(TargetFramework))</Product>
    <DefaultLanguage>en-US</DefaultLanguage>
    <NoWarn>$(NoWarn);1998;Uno0001</NoWarn>
    <GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
    <AssemblyName>Telerik.UI.Xaml.Primitives.UWP</AssemblyName>
	<OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
		<EmbeddedResource Include="BusyIndicator\Animations\*.xaml" />
		<EmbeddedResource Include="**\*.png" Exclude="bin\**\*.png;obj\**\*.png" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core.UWP\Telerik.Core.csproj" />
  </ItemGroup>

</Project>