<Project Sdk="Uno.Sdk">
  <PropertyGroup>
		<TargetFrameworks>net9.0-ios;net9.0-maccatalyst;net9.0-windows10.0.26100;net9.0-browserwasm;net9.0-desktop</TargetFrameworks>
		<Product>$(AssemblyName) ($(TargetFramework))</Product>
		<DefaultLanguage>en-US</DefaultLanguage>
    <NoWarn>$(NoWarn);1998;Uno0001</NoWarn>
    <GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
    <AssemblyName>Telerik.UI.Xaml.Controls.Data.UWP</AssemblyName>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core.UWP\Telerik.Core.csproj" />
		<ProjectReference Include="..\..\Data.UWP\Telerik.Data.csproj" />
		<ProjectReference Include="..\..\Input\Input.UWP\Telerik.Input.csproj" />
		<ProjectReference Include="..\..\Primitives\Primitives.UWP\Telerik.Primitives.csproj" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == 'MonoAndroid' or  '$(TargetFrameworkIdentifier)' == 'Xamarin.iOS' ">
		<Reference Include="Microsoft.CSharp" />
	</ItemGroup>

</Project>