<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetCurrentAll)</TargetFrameworks>
    <Product>$(AssemblyName) ($(TargetFramework))</Product>
    <DefaultLanguage>en-US</DefaultLanguage>
    <NoWarn>$(NoWarn);1998;Uno0001</NoWarn>
    <GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
    <AssemblyName>Telerik.UI.Xaml.Input.UWP</AssemblyName>
	<OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core.UWP\Telerik.Core.csproj" />
    <ProjectReference Include="..\..\Primitives\Primitives.UWP\Telerik.Primitives.csproj" />
  </ItemGroup>
</Project>